CREATE TABLE T_USER (
	ID INT ( 12 ) NOT NULL AUTO_INCREMENT,
	USER_NAME VARCHAR ( 60 ) NOT NULL,
	SEX INT ( 3 ) NOT NULL DEFAULT 1 CHECK ( SEX IN ( 1, 2 ) ),
	NOTE VARCHAR ( 256 ) NULL,
PRIMARY KEY ( ID ) 
);